# Generated by Django 6.0.6 on 2026-06-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=255)),
                ('deskrisaun', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kategorias',
            },
        ),
        migrations.CreateModel(
            name='Produtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=255)),
                ('deskrisaun', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtus', to='products.kategoria')),
            ],
            options={
                'verbose_name_plural': 'Produtus',
            },
        ),
    ]
