# Generated by Django 6.0.6 on 2026-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalloPedidu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kantidade', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Detallo Pedidus',
            },
        ),
        migrations.CreateModel(
            name='Pagamentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodu', models.CharField(choices=[('cod', 'COD (Selu Bainhira Simu)'), ('transfer', 'Transferensia Bankaria'), ('mbway', 'MBWAY')], max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('pagu', 'Pagu'), ('kansela', 'Kansela')], default='pendente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pagamentus',
            },
        ),
        migrations.CreateModel(
            name='Pedidu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('konfirmadu', 'Konfirmadu'), ('envia', 'Envia'), ('entrega', 'Entrega'), ('kansela', 'Kansela')], default='pendente', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endeereco_entrega', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pedidus',
            },
        ),
    ]
