# Generated by Django 6.0.6 on 2026-06-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalloPedidu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kantidade', models.IntegerField(verbose_name='Kantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotál')),
            ],
            options={
                'verbose_name': 'Detallu Pedidu',
                'verbose_name_plural': 'Detallu Pedidu sira',
            },
        ),
        migrations.CreateModel(
            name='Pagamentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodu', models.CharField(choices=[('cod', 'COD (Selu bainhira simu)'), ('transfer', 'Transferénsia bankária'), ('mbway', 'MBWAY')], max_length=50, verbose_name='Metodu')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totál')),
                ('status', models.CharField(choices=[('pendente', 'Hein selu'), ('pagu', 'Selu ona'), ('kansela', 'Kansela ona')], default='pendente', max_length=50, verbose_name='Estadu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
            ],
            options={
                'verbose_name': 'Pagamentu',
                'verbose_name_plural': 'Pagamentu sira',
            },
        ),
        migrations.CreateModel(
            name='Pedidu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Hein prosesu'), ('konfirmadu', 'Konfirmadu ona'), ('envia', 'Haruka ona'), ('entrega', 'Simu ona'), ('kansela', 'Kansela ona')], default='pendente', max_length=50, verbose_name='Estadu')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totál')),
                ('enderesu', models.TextField(default='', verbose_name='Enderesu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
            ],
            options={
                'verbose_name': 'Pedidu',
                'verbose_name_plural': 'Pedidu sira',
            },
        ),
    ]
