# Generated by Django 6.0.6 on 2026-06-19 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidu',
            name='kliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidus', to='users.kliente'),
        ),
        migrations.AddField(
            model_name='pagamentu',
            name='pedidu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentu', to='orders.pedidu'),
        ),
        migrations.AddField(
            model_name='detallopedidu',
            name='pedidu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallos', to='orders.pedidu'),
        ),
    ]
