# Generated by Django 6.0.6 on 2026-06-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Klientes',
            },
        ),
        migrations.CreateModel(
            name='Notifikasaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajen', models.TextField()),
                ('tipu', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasauns', to='users.kliente')),
                ('pedidu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifikasauns', to='orders.pedidu')),
            ],
            options={
                'verbose_name_plural': 'Notifikasauns',
            },
        ),
    ]
