# Generated by Django 6.0.6 on 2026-06-30 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Naran uzuáriu')),
                ('password', models.CharField(max_length=255, verbose_name='Liafuan-pase')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administrador sira',
            },
        ),
        migrations.CreateModel(
            name='Kliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=255, verbose_name='Naran')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Liafuan-pase')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Tama ikus')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Kliente',
                'verbose_name_plural': 'Kliente sira',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('role', models.CharField(choices=[('customer', 'Kliente'), ('admin', 'Administrador')], default='customer', max_length=20, verbose_name='Papel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Uzuáriu')),
            ],
            options={
                'verbose_name': 'Kliente (Sistema)',
                'verbose_name_plural': 'Kliente Sistema sira',
            },
        ),
        migrations.CreateModel(
            name='Notifikasaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajen', models.TextField(verbose_name='Mensajen')),
                ('tipu', models.CharField(max_length=50, verbose_name='Tipu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
                ('kliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasauns', to='users.kliente', verbose_name='Kliente')),
                ('pedidu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifikasauns', to='orders.pedidu', verbose_name='Pedidu')),
            ],
            options={
                'verbose_name': 'Notifikasaun',
                'verbose_name_plural': 'Notifikasaun sira',
            },
        ),
    ]
