# Generated by Django 6.0.6 on 2026-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
